pipeline {
    agent any

    environment {
        DOCKER_IMAGE = "nidhiphophaliya/book-service:latest"
    }

    stages {
        stage('Build Maven Project') {
            steps {
                dir('book-service') {
                    bat 'mvn clean install'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('book-service') {
                    bat 'docker build -t %DOCKER_IMAGE% .'
                }
            }
        }

        stage('Push to Docker Hub') {
            steps {
                dir('book-service') {
                    withCredentials([usernamePassword(
                        credentialsId: 'dockerhub-creds',
                        usernameVariable: 'DOCKER_USER',
                        passwordVariable: 'DOCKER_PASS'
                    )]) {
                        bat '''
                            echo %DOCKER_PASS% | docker login -u %DOCKER_USER% --password-stdin
                            docker push %DOCKER_IMAGE%
                        '''
                    }
                }
            }
        }

        stage('Deploy to Minikube') {
            steps {
                dir('book-service') {
                    bat 'kubectl apply -f k8s-deployment.yaml'
                }
            }
        }
    }
}
